# Use official Nginx base image
FROM nginx:alpine

# Remove default Nginx content
RUN rm -rf /usr/share/nginx/html/*

# Copy app1's HTML file to Nginx html folder
COPY index.html /usr/share/nginx/html/

# Expose port 80
EXPOSE 80
